- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present

- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana_ansible

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Start Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: started
    enabled: yes

- name: Update Prometheus URL in datasources.yaml
  ansible.builtin.copy:
    dest: /etc/grafana/provisioning/datasources/datasources.yaml
    content: |
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: "http://{{ ansible_host }}:9090"
        isDefault: true
        
- name: Restart Grafana service
  ansible.builtin.service:
    name: grafana-server
    state: restarted