- name: Create Prometheus system user and group
  ansible.builtin.user:
    name: "{{ prometheus_user }}" # CHANGED
    system: true
    create_home: "{{ prometheus_create_home | default(false) }}" # CHANGED
    shell: "{{ prometheus_shell | default('/bin/false') }}" # CHANGED
    state: present 

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "{{ prometheus_download_url }}" # CHANGED
    dest: "{{ prometheus_download_dest }}" # CHANGED

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: "{{ prometheus_download_dest }}" # CHANGED
    dest: "{{ prometheus_extracted_dir }}" # CHANGED
    remote_src: yes

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}" # CHANGED
    group: "{{ prometheus_user }}" # CHANGED
  with_items:
    - "{{ prometheus_data_dir }}" # CHANGED
    - "{{ prometheus_config_dir }}" # CHANGED

- name: Copy Prometheus binary
  ansible.builtin.copy:
    src: "{{ prometheus_extracted_dir }}/prometheus" # CHANGED
    dest: "{{ prometheus_bin_path }}/prometheus" # CHANGED
    mode: '0755'
    remote_src: yes

- name: Copy Promtool binary
  ansible.builtin.copy:
    src: "{{ prometheus_extracted_dir }}/promtool" # CHANGED
    dest: "{{ prometheus_bin_path }}/promtool" # CHANGED
    mode: '0755'
    remote_src: yes

- name: Copy consoles directory
  ansible.builtin.copy:
    src: "{{ prometheus_extracted_dir }}/consoles" # CHANGED
    dest: "{{ prometheus_consoles_dir }}" # CHANGED
    owner: "{{ prometheus_user }}" # CHANGED
    group: "{{ prometheus_user }}" # CHANGED
    directory_mode: yes
    remote_src: yes

- name: Copy console libraries directory
  ansible.builtin.copy:
    src: "{{ prometheus_extracted_dir }}/console_libraries" # CHANGED
    dest: "{{ prometheus_console_libraries_dir }}" # CHANGED
    owner: "{{ prometheus_user }}" # CHANGED
    group: "{{ prometheus_user }}" # CHANGED
    directory_mode: yes
    remote_src: yes

- name: Copy Prometheus configuration
  ansible.builtin.copy:
    src: "{{ prometheus_extracted_dir }}/prometheus.yml" # CHANGED
    dest: "{{ prometheus_config_dir }}/prometheus.yml" # CHANGED
    owner: "{{ prometheus_user }}" # CHANGED
    group: "{{ prometheus_user }}" # CHANGED
    remote_src: yes

- name: Create Prometheus systemd service unit file
  ansible.builtin.copy:
    dest: "{{ prometheus_service_path }}" # CHANGED
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      StartLimitIntervalSec=500
      StartLimitBurst=5

      [Service]
      User={{ prometheus_user }} # CHANGED
      Group={{ prometheus_user }} # CHANGED
      Type=simple
      Restart=on-failure
      RestartSec=5s
      ExecStart={{ prometheus_bin_path }}/prometheus \ # CHANGED
        --config.file={{ prometheus_config_dir }}/prometheus.yml \ # CHANGED
        --storage.tsdb.path={{ prometheus_data_dir }} \ # CHANGED
        --web.console.templates={{ prometheus_consoles_dir }} \ # CHANGED
        --web.console.libraries={{ prometheus_console_libraries_dir }} \ # CHANGED
        --web.listen-address=0.0.0.0:9090 \
        --web.enable-lifecycle

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'

- name: Start Prometheus service
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
