- name: Download node_exporter
  ansible.builtin.get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz

- name: Extract prometheus
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/node_exporter
    remote_src: yes


- name: Copy binary files
  ansible.builtin.copy:
    src: /tmp/node_exporter/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes


- name: Create Prometheus systemd service unit file
  ansible.builtin.copy:
    dest: /etc/systemd/system/node_exporter.service
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      StartLimitIntervalSec=500
      StartLimitBurst=5

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      Restart=on-failure
      RestartSec=5s
      ExecStart=/usr/local/bin/node_exporter \
        --collector.logind

      [Install]
      WantedBy=multi-user.target
    owner: root
    group: root
    mode: '0644'
    
- name: Start service node_exporter
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: yes


- name: Add Node Exporter as a target in Prometheus
  ansible.builtin.blockinfile:
    path: /etc/prometheus/prometheus.yml
    block: |
        - job_name: 'node_export'
          static_configs:
            - targets: ["localhost:9100"]
    insertafter: '^scrape_configs:'
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NODE_EXPORTER"
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Validate Prometheus configuration
  ansible.builtin.command:
    cmd: promtool check config /etc/prometheus/prometheus.yml
  register: validate_result
  failed_when: validate_result.rc != 0
  changed_when: false


- name: Reload Prometheus configuration
  ansible.builtin.uri:
    url: http://localhost:9090/-/reload
    method: POST
    status_code: 200
  register: reload_result


      




